name: Run tests
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.0'
      - run: go fmt
        name: Run go fmt
      - run: go vet
        name: Run go vet
      - run: go build
        name: Build code
